"""CLI tests: call cli.main([...]) directly with a throwaway XDG config dir.

Golden files under tests/golden/ hold the full report output. They were
generated by running the CLI once and reviewing the numbers by hand; to
regenerate after an intended change, run with TAXCALC_UPDATE_GOLDEN=1.
"""

import os
from pathlib import Path

import pytest

from taxcalc import cli
from taxcalc.config import Config, load_config

GOLDEN = Path(__file__).parent / "golden"


@pytest.fixture(autouse=True)
def xdg(monkeypatch, tmp_path):
    """Point the config dir at tmp_path so the real ~/.config is never read."""
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path))
    return tmp_path / "taxcalc"


@pytest.fixture
def configured(xdg):
    xdg.mkdir()
    (xdg / "config.toml").write_text(
        '[household]\ntarif = "married"\ncommune = "Zürich"\nchildren = 0\n', encoding="utf-8"
    )
    return xdg


def answers(monkeypatch, *replies):
    """Feed replies to input(); the prompts shown are collected in the returned list."""
    prompts = []
    remaining = list(replies)

    def fake_input(prompt):
        prompts.append(prompt)
        if not remaining:
            raise EOFError
        return remaining.pop(0)

    monkeypatch.setattr("builtins.input", fake_input)
    return prompts


def check_golden(name, output):
    path = GOLDEN / name
    if os.environ.get("TAXCALC_UPDATE_GOLDEN"):
        path.write_text(output, encoding="utf-8")
    assert output == path.read_text(encoding="utf-8")


def test_non_interactive_report(configured, capsys):
    exit_code = cli.main(
        ["--year", "2026", "--income", "150'000", "--assets", "500 000",
         "--federal-income", "155000"]
    )  # fmt: skip
    assert exit_code == 0
    check_golden("married_2026.txt", capsys.readouterr().out)


def test_non_interactive_with_children_and_overrides(configured, capsys):
    exit_code = cli.main(
        ["--year", "2025", "--income", "80000", "--tarif", "single", "--commune", "winterthur",
         "--children", "1"]
    )  # fmt: skip
    assert exit_code == 0
    check_golden("single_winterthur_2025.txt", capsys.readouterr().out)


def test_interactive_with_config(configured, monkeypatch, capsys):
    prompts = answers(monkeypatch, "2026", "150000", "500000", "155000")
    assert cli.main([]) == 0
    assert prompts[0] == "Tax year (2024–2026) [2026]: "
    out = capsys.readouterr().out
    assert "Settings: Verheiratetentarif, Gemeinde Zürich, 0 child(ren)" in out
    assert out.endswith((GOLDEN / "married_2026.txt").read_text(encoding="utf-8"))


def test_interactive_defaults(configured, monkeypatch, capsys):
    # Empty answers take the defaults: assets 0, federal income = cantonal income.
    answers(monkeypatch, "", "100000", "", "")
    assert cli.main([]) == 0
    out = capsys.readouterr().out
    assert "Steuerperiode 2026" in out
    federal_total = next(line for line in out.splitlines() if "Total direkte" in line)
    assert federal_total.endswith(" 1'816.00")


def test_interactive_reprompts_on_bad_input(configured, monkeypatch, capsys):
    answers(monkeypatch, "1999", "2026", "lots", "-5", "100000", "", "")
    assert cli.main([]) == 0
    err = capsys.readouterr().err
    assert "no tax rates for '1999'" in err
    assert "not a valid amount: 'lots'" in err
    assert "amount must be zero or positive" in err


def test_first_run_asks_settings_and_saves_them(xdg, monkeypatch, capsys):
    prompts = answers(monkeypatch, "2026", "married", "zurich", "2", "y", "100000", "", "")
    assert cli.main([]) == 0
    assert any("Tarif" in p for p in prompts)
    assert load_config(xdg / "config.toml") == Config(tarif="married", commune="Zürich", children=2)
    assert "Abzug für 2 Kind(er)" in capsys.readouterr().out


def test_first_run_can_decline_saving(xdg, monkeypatch):
    answers(monkeypatch, "2026", "single", "", "0", "n", "100000", "", "")
    assert cli.main([]) == 0
    assert not (xdg / "config.toml").exists()


def test_eof_reports_error(configured, monkeypatch, capsys):
    answers(monkeypatch, "2026")
    assert cli.main([]) == 1
    assert "no answer given for: Steuerbares Einkommen" in capsys.readouterr().err


def test_non_interactive_without_tarif_fails(capsys):
    assert cli.main(["--income", "100000"]) == 1
    assert "no tarif configured" in capsys.readouterr().err


def test_non_interactive_unknown_commune(configured, capsys):
    assert cli.main(["--income", "100000", "--commune", "Bern"]) == 1
    assert "unknown commune 'Bern'" in capsys.readouterr().err


def test_unknown_year(configured, capsys):
    assert cli.main(["--year", "2019", "--income", "1"]) == 1
    assert "no tax rates for 2019" in capsys.readouterr().err


def test_invalid_config_is_reported(xdg, capsys):
    xdg.mkdir()
    (xdg / "config.toml").write_text("not [valid toml", encoding="utf-8")
    assert cli.main(["--income", "100000"]) == 1
    assert "not valid TOML" in capsys.readouterr().err


def test_list_communes(capsys):
    assert cli.main(["--list-communes", "--year", "2026"]) == 0
    out = capsys.readouterr().out
    assert out.startswith("Steuerfüsse 2026 (Kanton 95%)")
    assert "  Zürich                         119%" in out


def test_rates_override_from_config_dir(configured, capsys):
    text = (Path(cli.__file__).parent / "rates" / "2026.toml").read_text(encoding="utf-8")
    (configured / "rates").mkdir()
    (configured / "rates" / "2027.toml").write_text(text, encoding="utf-8")
    assert cli.main(["--year", "2027", "--income", "100000"]) == 0
    assert "Steuerperiode 2027" in capsys.readouterr().out


@pytest.mark.parametrize(
    ("text", "amount"),
    [("123'456", "123456"), ("123’456.50", "123456.50"), ("CHF 1 000", "1000"), ("1_000", "1000")],
)
def test_parse_amount(text, amount):
    assert str(cli.parse_amount(text)) == amount
